package com.enterprisesys.plm.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotNull;


@Entity
@Table(name = "employees")
@JsonIgnoreProperties(ignoreUnknown = true)
public
class Employee {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter @Setter
    @JsonProperty("idEmployee")
    @Column(name="idEmployee")
    private Integer idEmployee;

    @NotNull
    @Getter @Setter
    @JsonProperty("firstName")
    @Column(name="firstName")
    private String firstName;

    @NotNull
    @Getter @Setter
    @JsonProperty("lastName")
    @Column(name="lastName")
    private String lastName;

    @Getter @Setter
    @JsonProperty("email")
    @Column(name="email")
    private String email;

    @Getter @Setter
    @JsonProperty("assignedToProjects")
    @Column(name="assignedToProjects")
    private String assignedToProjects;

    public Employee() { }

}