package com.enterprisesys.plm.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

import javax.persistence.*;
import javax.validation.constraints.NotNull;


@Entity
@Table(name = "parts")
@JsonIgnoreProperties(ignoreUnknown = true)
public
class Part {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Getter @Setter
    @JsonProperty("idPart")
    @Column(name="idPart")
    private Integer idPart;

    @NotNull
    @Getter @Setter
    @JsonProperty("partName")
    @Column(name="partName")
    private String partName;

//    The Part model contains the @ManyToOne annotation to declare that it has a many-to-one relationship
//    with the Assembly entity. It also uses the @JoinColumn annotation to declare the foreign key column.

    @Getter @Setter
//    @ManyToOne
    @JoinColumn(name = "idAssembly", nullable = false)
    @JsonIgnore
//    @JsonIgnoreProperties(ignoreUnknown = true, value = {"assemblyName", "object", "path"})
    @OnDelete(action = OnDeleteAction.CASCADE)
    @ManyToOne(fetch = FetchType.LAZY)
    private  Assembly assembly;

    public Part() { }

    public Part(Integer id) {
        this.idPart = id;
    }

    public Part(String name) {
        this.partName = name;
    }

    public Part(Integer id, String part) {
        super();
        this.idPart = id;
        this.partName = part;
    }

}
